### ISSUE TITLE
질문 앤티티의 Cascade 관련 문제

### ISSUE THREAD

**Issue by Sinawe4** [Amething/amething-server#10]
#6 에서 만든 Question 클래스에서 
```java
@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
@JoinColumn(name = "user_id")
    private User user;
```
이런식으로 다의 관계에 있는 앤티티에 `Cascade` 옵션을 넣으셨는데, 이런식으로 사용하면 안됩니다. 

> CascadeType.ALL에 `@ManyToOne`는 사용되어선 안됩니다. 엔티티 상태 전환은 상위 엔티티에서 하위 엔티티로 전파되어야 하며, 그 반대가 되어서는 안 됩니다.

해결방안으로는 이 방법을 제안합니다.
```java
@ManyToOne(fetch = FetchType.LAZY)
@OnDelete(action = OnDeleteAction.CASCADE)
@JoinColumn(name = "user_id")
    private User user;
```
이런식으로 사용하게 되면, 양방향 매핑을 사용하지 않고, Cascade 옵션을 사용할 수 있습니다!

참고한 레퍼런스입니다.
- https://stackoverflow.com/questions/13027214/what-is-the-meaning-of-the-cascadetype-all-for-a-manytoone-jpa-association
- https://myunji.tistory.com/m/492

**Comment by TeMlN** [comment]
확인 했습니다 현 작업 PR오픈하고 해당 내용 적용하겠습니다 @Sinawe4

**Comment by Sinawe4** [comment]
👍
